### ISSUE TITLE
Detect empy lists

### ISSUE THREAD

**Issue by bobbulman** [itmaybejj/editoria11y#18]
Can you add a check for empy list tags eg:
`<ul></ul>`

We have had a few occurrences of these being left in the rich-text editor fields so it would be good if you could detect them.

**Comment by itmaybejj** [comment]
Hi Bob!

VoiceOver at least ignores the empty `<ul>` -- seems to treat it as a `<span>`. I...tend to lean against HTML quality tests unless the issue presents an accessibility issue, just because I try to hide the HTML behind the curtain as much as possible for the editors. But I can be convinced...

In the meantime -- which CMS are you in? Some have built straightforward text filter functions or plugins that can be set to strip empty tags on save, e.g. [HTML Purifier](https://www.drupal.org/project/htmlpurifier).

**Comment by bobbulman** [comment]
Hi,

That’s interesting – we’re using Drupal 10 so I’ll look into that module!

Thanks again

Bob Bulman
Digital Programme and Website Officer
Westmorland and Furness Council | Service Centre
Parkhouse Building | Kingmoor, Carlisle | CA6 4SJ

Mobile: 07824 622775
Email: ***@***.******@***.***>
